[package]
name = "BNSongBot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
tokio = { version = "1.46.1", features = ["full"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
futures = "0.3.31"
